

let eq = document.getElementById("eq")
let get = document.getElementById("get")
let ans = document.getElementById("ans")



let data = [

    // 3 
    "While configuration we should not change cpe password page if it was admin:",
    "(False)",
    "The Problem of being APIPA working now instead of DHCP will be solved by Reset and Reconfiguration :",
    "(True)",
    "Which of the below is responsible for assigning automatic LAN IP`s to the private devices which are connected to the same CPE :",
    "(DHCP)",
    "That right connection, if the CST main wire comes from the box to the wall outlet, then it connects to a splitter, then connects to the phone set and CPE :",
    "(True)",
    "If cst has wall outlet connection .(CPE and phone set not connected from same wall outlet)  He must connect splitter or filter before any Phone set  :" ,
    "(True)",
    "which of the below is responsible for controlling the size of sent packets of data :",
    "( MTU )",
    "Which of the following is APIPA IP :",
    "(169.254.0.1)",
    "The Right Connection for the PBX is to connect it after the Splitter:",
    "(True)",
    "Which of the following responsible for fix welding from main wire :",
    "(Rosetta)",
    "In cpe configuration VPI =35 and VCI=0 :",
    "(False)",
    "We can use Ethernet cable only to make CPE Configuration:",
    "(False)",
    "which of the below is responsible for resolve from Domain to IP / Ip to Domain :",
    "(DNS)",
    "ADSL and VDSL CPE WAN configuration, is the same settings :",
    "(False)",
    "Device that connected before telephone set to isolate the traffic is known as :",
    "(Filter)",
    "The Telephone cable ends with RJ :",
    "(11)",
    "Device that used for adding data signal to customer's line to have data and voice is at same line :",
    "(DSLAM)",
    "In splitter, we should connect the CPE to the Line hole:",
    " (False)",
    " If the DHCP is not working now, which of the following will work instead of him :",
    "(APIPA )",
    "We have two types of connections (Main wire and wall outlet) :",
    " (True)",
    "The Ideal connection for main wire connection is coming the line from the BOX to CPE then splitter and telephone set  :",
    " (False)",


   // 4 

    " CCA can Adding a new Request through BSS from :",
    " (Sitmap >> integrated  operations >> check availability PSTN)",
    "Which tool show account status :",
    '(BSS)',
    'FCC Automatic TTs will be created if cst has a problem in any activity and CCA will inform CST ….. SLA and someone will follow with him:',
    '(24 H)',
    'In Case Cst asked to subscribe on Data & Voice with us ,, we Should not mark on Voice&Data Flag in check availability request :',
    ' (False)',
    '  Automatic Survey SLA :',
    ' (1 day)',
    ' In case CCA mistake when he make check availability request and need to modify this data  CCA action…:',
    '  Refer to SV to modify it and choose modify reason ( Operator Request )',
    'CST can request Landline Delivery service   for consumer through :',
    '  (ALL of the above)',
    ' We can follow up on check availability request result by :',
    ' (National ID OR Request SN)',
    ' CCA must inform CST required paper and new land line Fees when he make check availability :',
    '   (True)',
    '   We can follow up on check availability request result through BSS from…:',
    '(Sitmap >> integrated  operations >> search availability PSTN)',
    ' Call back to CRM activity means that order had installed/closed',
    '(True)',
    'Barring period for quarterly Prepaid customer :',
    '(3 Days)',
    ' Check availability request available through Branches,111, E-care and WE App :',
    ' (True)',
    'If Check availability result was not available and Survey is started that means :',
    '(Automatic Survey will be sent to project mangment to check availability)',
    ' The period of available for contracting in case availability result was available is..:',
    '(14 D)',
    ' in case Line is FTTH ,, contracting done firstly on Second Phone number (voice only) then contracting on the first Phone number (data & voice) :',
    '(True)',
    'There is SMS will be sent to cst contain Check availability request SN :',
    ' (True)',
    ' who can choose modify reason ( Operator Request ) ?:',
    '  (Supervisor)',
    ' In case request result was available& Expired   CCA Action.......:',
    '(Make modify (as Customer Request) to Re-activate the request)',
    ' When CCA make check availability request , CST did not know land line Num in the same building or cabinet Num … We must choose :',
    ' (Others)',


    ///  5 

    'CCA can change cst package by choosing :',
    '(Change Offering)',
    ' If customer need to cancel & refund the amount within the installation cycle for FV action done through : ',
    ' (branch)',
    ' While creating any TT not related to Complaint TT, we must choose additional information  .. ?',
    ' (Problem / non-om Problem)',
    ' CCA Can Add Salfni Service From …?',
    ' (BSS)',
    ' CCA Can Make SR or TT By choosing …',
    '  (Create Service Request)',
    " CCA Can Change CST's Mobile Number From BSS by choosing…?",
    '(Modify Subscriber Information + Modify Customer Information)',
    'CCA will press on ….. To create SR or TT?',
    '(submit)',
    'the period of temporary suspension for Quarter new consumer FV CST is:',
    ' (210 D)',
    'CCA  can resume the service if cst (Suspend / Bar) as per cst request from : ',
    ' (BSS)',
    '    CCA can make resume and unbar to …?',
    ' (Remove requested suspend)',
    "IF consumer CST didn't pay his quarter land line bill, line will be on Status BAR For…",
    '(3 D)',
    'SR status must be …. ?',
    '(Open)',
    'Bar upon customer request done through : ',
    '(All of the above) ',
    'CCA should not inform cst about required papers to Change the Landline category from home to commercial:',
    '  (False)',
    ' Change Ownership for landline done from ...?',
    '(Branch)',
    'CST can pay his bills through : ',
    '  (All of the above )',
    ' Change location as per CST request only done if cst subscribed in voice only or Data and voice from WE : ',
    ' (True)',
    'The Grace period for postpaid CSTs is ?',
    ' (20 Days)',
    ' CST can subscribe on Postpaid rate plan for land line subscription:',
    ' (True)',
    ' What fees for Bar landline upon customer request :',
    '(10 without tax)',

    //  6

    '     Which of those packages is Corporate One Invoice .. :', 
    '    (Corporate Super speed 1 - (140 GB) – AL )', 
    'Which tool can we use for checking TE bills?', 
    '    (BSS Tool)', 
    'What is the current price of the available router?', 
    '    (1710 with VAT)', 
    'We can search on new cst 360 using Adsl number :', 
    '    (True)', 
    'Start speed for Super up to 30 is :', 
    '    (8 Mbps)', 
    'Way of subscription to internet service is ....?', 
    '    (Branches)', 
    'CST can make Early renewal for Super 20 GB ', 
    '    (False)', 
    'Postpaid corporate One invoice Bill cycle is …. ?', 
    '    (Day 1 or Day 22 from each month) ', 
    'If CST eligible for (door to door) , your action:', 
    '    (create TT)', 
    '    From which tool CCA can check Outage :', 
    '    (New CST 360)', 
    '    From which tool can check ADSL led Up or Down (port operational status )', 
    '    (New cst 360)', 
    '    Optimization period for super up to 30 VDSL IS:', 
    '    (4 days)', 
    '    Corporate one invoice CST can add Extra Quota through .. ', 
    '    (Mobile APP)', 
    '    Super 140G has watch it for free?', 
    '    (False)', 
    '     is up to 70M?', 
    '    (Mega)', 
    '    The only condition for a customer to be considered eligible for the Door to Door service is that they must be over 65:', 
    '    (False)', 
    '    CST can make Early renewal for Super 100 GB through ….', 
    '    (Mobile App &E-care)', 
    '    Which of the following speeds is considered ADSL?', 
    '    (Super 1)', 
    '    If CST has Contracted with us , Installation phase for order ( Internet service ),,MSAN Line will be done within :', 
    '    (5 Days)', 
    '    All Exchanges eligible for (door to door) ….. ', 
    '    (False) ' , 


    // 7 

    'SLA For TE Problem Is .....', 
    '    (7 WD)', 
    'If CST need change Package Before Installation It is mandatory to CCA To Verify With Customer:', 
    '    (True)', 
    'In Case Of Delay In Port Splitting Activity CCA Action Will Be…?', 
    '    (Create TT And Inform CST new subscription SLA again)', 
    'CCA Can Make SR or TT By choosing …', 
    '    (Create Service Request)', 
    "CCA Can Get CST's Account Number from BSS ONLY?", 
    '    (False)', 
    'Cst has order in OM tool with status ( no data in both system),no order FV Found on OM,,', 
    '    (Inform CST 7 WD + Create SR)', 
    'CCA can Search by account number on BSS Tool?', 
    ' (False)', 
    'If customer has problem in My WE Activation SMS , and CCA do all T.S required from WIKI ,,CCA will Escalate the case  to BO and if there is update from BO that case was escalated to IT  CCA will inform cst with sla ........ :', 
    '    (72 H)', 
    'Line Problem SLA Is .....', 
    '(15 WD)', 
    'WO Request means That order waiting for … ?', 
    '(Work order)', 
    'If Cst Solve the problem that happened in order installation CCA action will be … ?', 
    '(Add Midway Comment And Create SR / Inform CST SLA 1WD)', 
    'In Case Of Delay In activity WO Request CCA action will be ….?', 
    '(create TT and inform CST SLA 1WD)', 
    'CST can use WE app for …?', 
    '(All answers are right)', 
    'Verification Rules when cst was calling from same Landline and need Extra Package .....', 
    '(Name on BSS)', 
    'IF cst already subscribed with us which Automatic TT Will be Created…?', 
    '(Automatic TT-FBB ----- WO problem ---- CST Problem - Already Subscribed)', 
    "CCA can check SR's history from ….", 
    '(Query Request)', 
    'change cst package with High amount within installation period Can Do Via...…', 
    '(From CSO)', 
    'Customer can get US & PW from IVR 3 times per day :  ', 
    '(False)', 
    'CST Can Change ….From My WE :', 
    '(Mobile Number & Mail)', 
    "Voice Provisioning Configuration It's an automatic activity before Network Activation", 
    '(True)',



    /// 8 

    "     In case Cst in Barring Period in last 2 days Next step ....." , 
    "    (Ask CST to pay landline bills and stop T.S)" , 
    "      Way of communication if cst has escalated Voice case:" , 
    "    (Call or SMS or Recorded message)" , 
    "      RE- Escalation SLA for voice down " , 
    "    (1 D)" , 
    "Voice down case will be escalated to IU with ….. Status" , 
    "    (Open)" , 
    `If the customer consumed the all package resources, the customer can't make a call until renewal and if complained from voice down " sending and receiving " CCA action...... `, 
    "    (escalate the case normal)" , 
    "While escalation of voice down should inform cst to leave CPE power turned on ?" , 
    "    (False)" , 
    "The caller ID is not recognized while the customer subscribed on this service CCA Action Will be" , 
    "    (Make T.S with CST and If not solved Create TT)" , 
    'In case customer asked to change main wire as it"s not long enough which SR you will create ..?' , 
    "    (FBB Tech Problem-​Voice Down-​Change Main Wire From Box)" , 
    "Migrated CST Called you has  voice down (sending and receiving) , check package status :Active , cst consumed his quota Your Action …" , 
    "    (Continue Troubleshooting)" , 
    "    CST has noise problem not related to physical issue after checking from cordless phone set no noise detected CCA next action will be  …?" , 
    "    (Create SR Phone set problem)" , 
    "    CST has noise problem not related to physical issue and hasn't cordless phone set  CCA  action will be  …?" , 
    "    (Let customer check with another phone set and feed us back)" , 
    "    Incase customer requests to change main wire without any technical problem, CCA should Escalate TKT normally:" , 
    "    (False)" , 
    "    CST said that when he pickup the phone to call anyone he hears a sound of Music  (weird voice case) CCA action will be …?" , 
    "    (Escalate as Voice Down)" , 
    "    You can check the land line bill for not migrated CST from as first priority.. " , 
    "    (Customer profile management )" , 
    "    In case CST informs us to not close the ticket till testing the service from his side Which SR CCA will create?" , 
    "    (FBB Tech Problem ---- ​​​Voice Down --- ​​CST will test the service)" , 
    "     CST called US and complain that he has recorded message, CST paid  his land line bill ,FV Status on new CST360 is Suspend ALL, CCA Action will be …?" , 
    "    (Remove Temp Suspension from CST360)" , 
    "     Incase Customer requests to change main wire due to technical problem, " , 
    "    (CCA should follow the technical problem.)" , 
    "      CST has a voice down ticket in IU and passed the  SLA, SR will be" , 
    "    (FBB Tech Problem---​Voice Down ---Follow Up After SLA)" , 
    "     TDM Line blocked on matrix and CST has unpaid internet bill CCA action will be …?" , 
    "    (Inform CST to pay internet bill)" , 
    "     CST has physical instability Issue and in the same time has voice down CCA action will be …?" , 
    "    (Escalate Voice down TT + Mention Troubleshooting In TTS Logs)" ,


    ///  9


    `If you escalate ticket to IU with no troubleshooting because of cut cable , way of communication will be:` , 
    `    (Call or SMS or Recorded message)` , 
    `CST has data down case with IU update and the ADSL led down within the call so your action ` , 
    `    (Run SELT Test again and check the distance more than or less than 10M or 150M)` , 
    `SLA for internal wiring TT:` , 
    `    (??)` , 
    `If Data Down case need to be escalated for the third time SLA will be:` , 
    `    (1 day)` , 
    `If power led is down and CST uses original adapter next step will be:` , 
    `    (Try in another wall-plug)` , 
    `If we run SELT and customer's line connected with exchange you will measure distance with:` , 
    `    (150 meters)` , 
    `Power Failure means:` , 
    `    (Power led not working or working with red color)` , 
    `CCA can reach to Data down case from WIKI by pressing on :` , 
    `    (Technical > Front line > physical cases > Data Down cases )` , 
    `If CST called us and informed that he has stolen cable and no outage on new  CST360, you will consider the case as:` , 
    `    (Data and Voice Down)` , 
    `    If CST has Data Down case and when you checked SELT you found that CST is not supported by ASSIA you will:` , 
    `    (Check connection type)` , 
    `    If CST has Data Down Case and connected form main wall outlet then problem solved you will: ` , 
    `    (Create TT for Pilot follow up team and inform CST with 2 hours SLA)` , 
    `    If CST has Data and Voice Down case after connect from main wall outlet problem solved you will:` , 
    `    (Create TT for internal wiring)` , 
    `    If CST informed that he has cut cable outside the flat, no need to check landline bills and escalate to IU directly:` , 
    `    (FALSE)` , 
    `    you can get IU update from TTS by choosing ` , 
    `    (Item logs )` , 
    `    CCA follow with cst Data Down case and the electricity is cut off during troubleshooting ,,CCA will create SR ` , 
    `    (FBB Tech Problem -Data Down -CST cannot troubleshoot - Electricity Issue)` , 
    `    CST complain from Data Down case and you found major fault in ADF Tool , your action :` , 
    `    (Act according to major fault process with attach screenshot from major fault message on SR)` , 
    `    During the maintenance visit , the technician Should check the internal wiring or Change CPE:` , 
    `    (FALSE)` , 
    `    If CST has Data Down and Power Failure ticket title & Category will be:` , 
    `    (Data Down - Power Failure)` , 
    `     Which tool you can get IU update from ….` , 
    `    (TTS)` , 
    `     If CST called us and informed that he has cut cable you will follow normal troubleshoot in ticket maker:` , 
    `    (FALSE)` , 


    /// 10 


    `        While follow with cst WCAP Case and Cst Line Status is Down and Matrix /New CST 360 Status is UP ,  so the next step is : ` , 
    `    (Follow Data status from main Step)` , 
    `    Ticket Wrong Card and Port second escalation will be escalate to :` , 
    `    (IU Maintenance)` , 
    `    Way of communication for Installation Visit  …` , 
    `    (Phone call.)` , 
    `    Customer from (Aswan) has a technical visit and passed SLA ..Your action:` , 
    `    (CCA should Inform the Customer with 1 Day SLA and create a delay ticket.)` , 
    `    In Case Customer follow on his ticket Within SLA for Re-escalated ticket , So the right SR :` , 
    `    (FBB tech problem>wrong card & port>follow up after re-escalation - within sla)` , 
    `In case WCAP CST disconnect phone cable from CPE and ADSL still UP , It is CPE Problem : ` , 
    `    (TRUE)` , 
    `You can get WCAP case from WIKI using tree:` , 
    `    (Technical > Front line > physical cases > Wrong card and port )` , 
    `Cst called you and  Adsl led in CPE is: UP , And matrix / cst 360  is: Up  and while you make restart port adsl led status didn"t match  matrix /cst 360 status so cst problem will be :` , 
    `    (Wrong card and port)` , 
    `Customer Follow up his ticket (Wrong Card and Port) and the TKT Has update Major Fault within First SLA , So right SR :` , 
    `    (FBB Tech Problem>Wrong card and port>Major Fault within SLA)` , 
    `    In Case WCAP case solved after cst connect from main , So the right SR :` , 
    `    (FBB Tech Problem>Wrong Card & port>Solved after connected from main)` , 
    `    CCA will Re-escalated ticket (Wrong Card and Port) to IU , So the right SR :` , 
    `    (FBB Tech Problem>Wrong Card and port>Re Escalation)` , 
    `    CST need Technical Visit Right TT will be:` , 
    `    (Boradband->Techncial->ADSL/VDSL->Creator->Technical Visit)` , 
    `    In case CST has TKT with update Major Fault Problem with estimated time 4 Months , CCA right action  :` , 
    `    (Will inform cst with no estimated time)` , 
    `    Cst has Ticket Data Down with Update ( Morkzat ) , So CCA will Inform cst with SLA :` , 
    `    (3 Days)` , 
    `    Way of Communication for Technical Visit will be call only..?` , 
    `    (TRUE)` , 
    `    In case CCA escalate ticket to Pilot - Follow up ,, SLA will be :` , 
    `    (??)` , 
    `    Cst has Ticket WCAP in IU Pool and TKT Passed SLA , So CCA will inform cst SLA : ` , 
    `    (??)` , 
    `    While Escalate Ticket WCAP to IU , TTS status will be :` , 
    `    (Open)` , 
    `    Cst need Installation Visit and after you make selt , result was 5M tkt will Escalate to :` , 
    `    (IU Maintenance)` , 
    `    cst called you has WCAP at the same time has voice down .. Your action:` , 
    `    (Escalate Voice down and mention the WCAP problem)` , 



    // 11 

'If CST complain physical instability and Power disconnects while service is down Your action :', 
 'Follow Power Failure with cst', 
 'In case real time clear view was : technical dispatch and after connect from main wall outlet became : No DSl physical layer ,,, CCA Action', 
 ' Escalate internal wiring-physical instability', 
 'While escalating Physical Instability CCA Must inform customer to keep his CPE turned on :', 
 'FALSE', 
 "In Case CST has physical instability TKT and has update ( visit performed) and within 2 days from update cst call us and inform us he didn't get visit , CCA Action", 
 "re-escalate the ticket to IU with updating the customer's input", 
 'Customer has ticket Physical Instability in IU , CCA informed him that he within SLA , Right SR is :', 
 'FBB Tech Problem > ​​Physical Instability > ​Follow Up', 
 'Third Escalation of Physical Instability case , SLA will be :', 
 '1 Day', 
 'Escalating Physical Instability Contradiction to .....', 
 'IU', 
 'No need to check (Faults Exist) before escalate physical instability ', 
 'FALSE', 
 'Third Escalation of Physical Instability case will be to Second level advanced ?', 
 'FALSE', 
 'CST complain from Physical instability adsl led down within call .. Your action ', 
 'Query NST For The Past 12 Hours, Is there 3 logs exist during last 12 hours with minimum 1 log during last 3 hours', 
 'Delay SLA for Physical Instability is …?', 
 '1 Day', 
 'In case has Physical Instability Contradiction and  we are waiting customer 2 min without responding and CCA ended the call​​ .. Right SR Will be …', 
 '​FBB Tech Problem ​- Physical Instability Contradiction ​- no respond from customers side for 2 Min', 
 'CCA must inform customer with ticket number while escalating Physical Instability case :', 
 'TRUE', 
 'while you follow physical instability with cst and  there is major fault in ADF Tool Your action is ..', 
 'Act according to major fault process with attach screenshot from major fault message on SR', 
 'Voice is not working also cst has physical instability  you will consider the case:', 
 'Voice Down', 
 'while troubleshooting physical instability , Clear View Result After Search "Technical dispatch is recommended " ,, next action is :', 
 'Check connection type', 
 'Cst has physical instability case with IU update represents a fix done(Ganzara removed), cst Supported By ASSIA , After connecting from main  and run Assia Result was (Technician Dispatch) Your Action', 
 'Re-Escalate the Ticket to IU Pool', 
 'while troubleshooting physical instability , connection type : wall outlet , the next step is :', 
 'Check if connection Right or Wrong', 
 'Third Escalation of Physical Instability case will be to  :', 
 'IU', 
 'while troubleshooting physical instability Contradiction , No Faults Exist , CCA will advise customer to check with another CPE , if not available with CST another cpe , right action is :', 
 'Direct customer to check his CPE In CSO and get test CPE if needed', 


// 12 


'While Troubleshoot BLQ case and line not Supported by assia , attainable speed more than Satisfactory and Operational speed less than Satisfactory speed so the next step is :', 
' Inform Customer To Check With Another CPE', 
'CCA must Ask customer for 1 mobile number while escalating Physical Instability case  :', 
'FALSE', 
'Way of communication while escalating BLQ case will be (Call / SMS) Only?', 
'FALSE', 
'BLQ first time escalation will be to', 
'IU Maintenance', 
'IF customer number belongs to Haya Karima and you will escalate to BLQ to Customer. right SLA Will be :', 
'3 Days ', 
'CST has BLQ ticket with update Welding Removed and no change done from cst side and after run assia clear view , result was No DSL physical layer issue detected so you will :', 
'Re-Troubleshoot as BLQ Supported By ASSIA in Ticket Maker.', 
'We should inform CST to leave CPE turned on while escalating BLQ case?', 
'FALSE', 
'Escalate Need Optimization case will be to …', 
'Pilot-SLS', 
'CCA should attach screen shot from matrix&CST360 ( Attainable & Configured Speed ) in case not Supported by Assia.', 
'TRUE', 
'In Case Assia Clear view Result after run Fix is No DSL Physical Layer is detected , Line Code is set to VDSL , Line is Stable from Line details and Operational speed Less than the Service Recommendation Speed , So CCA need to escalate :', 
'Need Optimization', 
'In BLQ case Clear View Result After Search is ( Technical dispatch is recommended ) , and after running the appropriate mode of Clear View result became ( No DSL Physical Layer is detected ) right action is :', 
'Check Diagnostic Tab In Line Details', 
'CST has BLQ ticket with update ( working from exchange ) without a visit update , right action is :', 
'Re-escalate case to IU pool', 
'In Case Assia Clear view Result after run Fix is (No DSL Physical Layer Issue Is Detected ), no faults exist, ,  Operational speed is less than contracted speed ,Port (VDSL).. next action ', 
'Check Line Code in ASSIA is set to VDSL2 ( G_993_2_Annex_B ) Step.', 
'CST has BLQ  subscripted on Super _ Up to 30Mbps , line not Supported by Assia and line type VDSL  Satisfactory level speed will be ', 
'20 Mbps', 
'Second time Escalation SLA in BLQ case is :', 
'1 Day', 
'Customer asked that the Internet working but slow and after CCA check Quota found that customer Exceeded Quota , So CCA right SR is :', 
'FBB Tech Problem>Slowness-Download>Exceed Quota', 
'In case you will Escalate Need Optimization case Way of communication will be ', 
'Call or SMS or Recorded message.', 
'CST has ticket Need Optimization escalated in 10.00 PM and CST calling at 11.30 pm in same day so you will :', 
'Inform cst waiting SLA', 
"Bad Line Quality ticket with update (Visit Performed)  yesterday .  and Customer called us after 2 days . and informed that he didn't get the visit , So CCA right action is :", 
"CCA will Re-escalate the ticket to IU with updating the customer's input", 
'cst has Ticket in IU pool and passed SLA so you will:', 
'Create delay ticket and inform cst sla 1 day', 







 // 13 


 'Recurring Recharge extra quota valid for', 
 'ADSL , VDSL , FTTH', 
 'CST can subscribe to two Giga Tank plans at the same time.', 
 'TRUE', 
 'Corporate one invoice need to change his Package CCA Right Action', 
 'Direct CST to authorize person ', 
 'No need to verify with CST if he/she need to change mobile number ?', 
 'FALSE', 
 'CST can change ….. From 111 .', 
 'Mobile number and Email', 
 'Corporate Customer ( individual ) need to change speed CCA right action ?', 
 'Create TT and inform cst 24whrs ', 
 'CST can make change package Before Due Date Via ……', 
 'All of the above', 
 'CST can make change ( mobile number &  e-mail ) through :', 
 'All of the above', 
 'Salfny service valid for  … ', 
 '2 days', 
 'If CST need to Change speed requires Change Port On or After Due Date or Suspend Life Cycle. What is the right action ?', 
 'We will inform the customer that he pays for the current package and requests the change at least 7 days before the renewal date', 
 'Corporate customers are eligible to subscribe to Giga Tank.', 
 'TRUE', 
 'Salfny service available for Corporate (One invoice & Individual ) and Postpaid Customers', 
 'false', 
 'if CST need to make change package with Higher or Same Amount Not Required Change Port after due date Via 111 CCA should suspend account and  inform cst to Recharge and call us within….', 
 '1 H or Less', 
 'CST can Correct name or ID number from .. ', 
 'Branches', 
 'Account status should be active if CST need to change mobile number ?', 
 'TRUE', 
 'Corporate Customer ( individual ) Can change speed On Spot from  111 ?', 
 'FALSE', 
 'In case Delay in change VDSL port CCA right action is ?', 
 'Create Delay TT', 
 'No required paper needed for changing package via stores ?', 
 'FALSE', 
 'Salfny service can be used twice within 30 days ?', 
 'FALSE', 
 'CST can Change Contact Name from ..', 
 'Branches',

 


    // 14 

    'We should follow Logical Verification before escalate unable to obtain ip case ', 
    'TRUE', 
    ' IF you face any issue in HDM Portal the SR  must contain a snapshot of the error', 
    ' TRUE  ', 
    ' CST has Unable To Obtain IP Case and subescribed on Option back right action', 
    'Transfer to option back Q', 
    'In case of Unable To Obtain IP while follow T.S MAC not learned next action will be ', 
    'Reset CPE hard and reconfigure', 
    'In case line on HDM offline right action will be', 
    'should restart Port', 
    'We Can check if cst obtained IP from ', 
    'NST from CST 360 TOOL', 
    'CCA should make verification if he will make any changes in WIFI configuration or Reset CPE', 
    'TRUE', 
    'In Case Unable To Obtain IP  Router ADSL LED matches with CST 360 Status while restarting ', 
    'TRUE', 
    "It's not  mandatory to use HDM Portal in Reset, Restart & Configure WLAN", 
    'FALSE', 
    'In case Unable To Obtain IP while follow T.S MAC Learned next action will be ', 
    ' Ask customer if there is any changes on CPE configurations', 
    '​In case CPE obtained IP after restarting the port and service works fine right SR will be ', 
    'FBB Tech Problem>Unable to Obtain IP>​Restart Port', 
    "All WE CPE's support HDM function ", 
    ' True', 
    '    We Can Change MTU from', 
    '   WAN Setting', 
    '  unable to obtain ip case cst should follow with us', 
    '     FALSE', 
    '     If HDM is opened with CPE data but faced any action issue we will direct cst to the branch', 
    'FALSE', 
    'SLA For unable to obtain IP', 
    '2 hours', 
    'Which actions is supported by HDM tool', 
    'Reset CPE', 
    'While escalating Unable to obtain IP  CCA Must inform customer to keep his CPE turned on ', 
    'TRUE', 
    'We can Check if MAC is learned or not from', 
    'CST 360 TOOL', 
    'In Case CCA will escalate Unable To Obtain IP Case at 2 PM , CCA not mandatory to check on call Before escalation', 
    'True', 





    // 15 

    'CST has browsing case (one site only is working) cst has', 
    'browsing all site', 
    'Browsing - All sites Case  will Re-escalate to :', 
    'NOC', 
    'In Case CCA will escalate Browsing - Certain site Case at 12 PM , CCA not mandatory to check on call Before escalation :', 
    ' TRUE', 
    ' Its mandatory to inform cst let cpe turned on within escalation browsing case', 
    'TRUE', 
    'Google DNS IS ?', 
    '8.8.8.8 /// 8.8.4.4', 
    'If cst was the owner of the website and reserve domain/ Hosting with WE CCA action ..', 
    'Transfer customer to Mail & Domain Q.', 
    'CST should Disable CPE Firewall and Activate ping option on CPE page - if available before escalate Browsing - all sites . ', 
    'TRUE', 
    'Way of communication for Browsing case ( ​All Sites - ​Certain Sites )', 
    'Call or SMS or Recorded message ', 
    'Trace Customer WAN IP will be done through .. ', 
    'Agent side', 
    'For Escalation Browsing all site case TT Will be  ?', 
    'Broadband->Technical->ADSL/VDSL->I Care->Browsing', 
    'browsing Certain Sites is ​Customer up with no network problem, but can"t browse any site?', 
    'FALSE', 
    'CCA should not inform customer with escalation ticket number in first escalation . ', 
    'FALSE', 
    'customer can open YouTube / Facebook but contents doesn’t appeared ,,first step is ??', 
    'IF CPE accessed try to adjust MTU and DNS [WE then Google DNS]', 
    "While escalate Browsing - Certain site Case , CCA shouldn't check and mention on call Before escalation (Note: Escalation in 6 PM)", 
    'FALSE', 
    'No problem from network side update found on Browsing case CCA first action is .. ', 
    '​Check MTU and add DNS on CPE page', 
    'If CST has Browsing case related to certain site case will escalated to ::', 
    ' SLS', 
    'If CST Ping Google Domain gave No Reply then Ping Google IP gave Reply from Google IP so next step is …', 
    'Do Flush DNS command ', 
    'Delay SLA for Browsing - All sites  is :', 
    '2 H', 
    'In case Customer input  that he paid the package bill within 24 hours, and line is Active on BSS, and Get Online Service on CST360/Matrix Not Blocked.', 
    'Restart Port', 
    'IF Redirection page Case not solved tkt will escalated with SLA', 
    '72 H',




    // 16 

 'Incase customer is facing  online gaming issue CCA should as first step:', 
 ' Check last fix date according to TTS and customer input at same time', 
 'If customer asked about VPN you will inform him ', 
 'Please note that due to technical reasons, you may face some difficulties while using the VPN over internet service in Egypt"', 
 'When CCA follow logical instability T.S with CST . CST must connect one laptop through wireless', 
 'FALSE', 
 'Incase customer is facing gaming issue no fault and has ping issue next action will be ', 
 'Adjust MTU to 1420', 
 'In case cst has many accepted logs in last 24 Hr , cca must be sure that not related to  restart port or cpe', 
 'TRUE', 
 ' IF the customer has many numbers of accepted logs in the previous 24hrs not related to restart port or cpe handle as a multiple login', 
 'TRUE', 
 'Incase customer is facing gaming issue and has ticket on IR still In Progress right action will be ', 
 'CCA will inform customer that Gaming team is currently checking his case and they will contact him shortly', 
 'SLA for Unsupported Services', 
 '2H', 
 'Unsupported Services Ticket Status Will be ', 
 'Waiting for research', 
 'Way of communication for Unsupported Services', 
 'Call ', 
 'Line Supported by ASSIA and clear view result was ( Technical dispatch ) , CCA Action', 
 'Handle physical instability problem', 
 'Escalation of logical instability ( multiple login ) must be to …', 
 'NOC ', 
 'Unsupported Services will be escalate to ', 
 'second level advanced', 
 'Incase customer  has ping issue solved by MTU right action will be ', 
 'create ticket on I report& SR ', 
 'if customer not beside CPE or CPE not connected right SR will be ', 
 'FBB Tech Problem >Logical Instability >​​​Not beside CPE', 
 'while escalation of logical instability No multiple login case. SLA is', 
 'From 2:5 H', 
 'Escalation of logical instability ( NO multiple login ) must be to …', 
 'SLS', 
 'In CASE CST has locked CPE we can direct him to cso ', 
 'FALSE', 
 'Incase customer is facing gaming issue and while T.S line congested or within ratio right action will be ', 
 'Deliver congested  script to customer', 
 'SLA for gaming Q will be ', 
 '15min',



    // 17 

 'If CST has  more than one device while T.S Slowness Case CCA Action', 
 'All of above', 
 'In Case problem is solved after ​enable wlan button , so the right SR :', 
 'FBB Tech Problem>Wireless>Enable WLAN Button', 
 'In case cst his Ping Google IP Result 0% loss and his CPE not supported by HDM Next Step Will be :', 
 'Trace Google from customer side Using cable', 
 'CCA can direct the customer to our CSO to configure the locked router by another company.', 
 'FALSE', 
 'In Slowness case CST Can make Trace Step Using Wifi ?', 
 'FALSE', 
 'Check POP Utilization Status From : ', 
 'Matrix Tool for TDM / CST 360 for Other lines', 
 'If CST has Wireless problem (  No WLAN detected ) and WLAN led status is On next step .. ', 
 'Check if SSID was hidden ', 
 'After follow slowness case TS, Customer download not accepted CCA Action :', 
 'Ping google IP', 
 'In case cst has Ping result from Google IP 35% , and there was packet loss from CPE IP , and the problem solved after make Reset & Reconfigure , So the right SR will be :', 
 'Logical Instability', 
 'In case cst has wireless issue and  the electricity is cut off during troubleshooting so right SR', 
 'FBB Tech Problem>Wireless>​CST cannot troubleshoot - Electricity Issue ', 
 'In case cst has slowness in Browsing After Adding Google DNs not solved CCA Action :', 
 'Adjust MTU to 1420', 
 'If CST has Wireless problem ( Unable to Connect to Wireless  ) first step will be .. ', 
 ' Reset and Reconfigure CPE', 
 'If the customer uses Youtube app or IDM (Internet Download Manager) or any application specialized in download) : no need to download 3 files if speed is not accepted with 1 file', 
 'TRUE', 
 'If customer was just asking about the existence of utilization problem in the pop, you can answer his/her question only without any troubleshooting.', 
 'TRUE', 
 'In Case Customer only ask about his wireless password < so the right SR :', 
 'FBB Tech Problem>Wireless>Need WI-FI User Name or Password', 
 'Slowness Case Escalated To : ', 
 'NOC', 
 'In case customer asked to configure wireless and the steps not done , So the right will be :', 
 'FBB Tech Problem>Wireless>​Wireless Configuration – Not done ', 
 'CST has issue in Streaming  your Action :', 
 'Check streaming on YouTube on Auto Quality', 
 'CST was using wireless and has download Issue CCA Action your action :', 
 'Ping Cpe Ip -t To  make sure that respond time less than or egual <= 2and Lose 0%', 
 "In case wireless problem is solved without troubleshooting and there is no other technical issue effects on customer's line according to his input/system so right SR", 
 'FBB Tech Problem>Wireless>Solved without T.S',



    // 18 

'In case any tool became down within T.S except BSS tool, CCA will create SR', 
 'FBB Tech Problem>>Outage – tool>>​Wrap up message', 
 'In case customer follow up after the wrap up ( BSS down ) CCA will', 
 'continue the troubleshooting which exist on iReport ', 
 'in case of Wrong Matrix Profile NO need to Attach the Matrix or CST 360 snapshot in TT', 
 'FALSE', 
 'CST has Access denied on CST 360 (MSAN Line) ,,there is no Outage on CST360 ,, no record on IR ,,CCA Right Action: ', 
 'All of the above ', 
 '(TDM Line) ,,CST has Wrong Matrix Profile and at the same time has data down CCA action:', 
 'All of the above', 
 'In case BSS became down within troubleshooting with customer right action ', 
 'CCA will update full troubleshooting steps done on iReport TKT', 
 'SLA for tools outage ', 
 'After 1H', 
 'SLA for  Wrong Matrix Profile', 
 '2h', 
 'SLA for no password in C360', 
 '1D', 
 'We can check outage from ', 
 'New CST360', 
 'CST has Access denied on Matrix (TDM Line) ,, ADSL Led up while Customer Not obtained IP or has no logs on NST ,,CCA right action :', 
 'Reset & configure', 
 'CCA should handle wireless case only in case the line is down with planned down outage', 
 'TRUE', 
 'in case no password in C360 CCA action will be ', 
 'Create  ticket on IR ', 
 'Submit error on BSS tool while escalating TT with no creation on TTS ,,CCA right action ::', 
 'Create IR record and inform CST 3 days ', 
 'Way of communication while escalate Wrong Matrix Profile', 
 'Call or SMS   ', 
 'in case of Wrong Matrix Profile ticket status changed to "waiting for IT" SLA will be', 
 '72 WH', 
 'Unplanned outage ​Already pre-announced outage with specific time', 
 'FALSE', 
 'Wrong Matrix Profile issue escalated to :', 
 'NOC', 
 'TDM Line,, CST has Access denied on Matrix ,, there is Outage Down management on CST 360,, CCA right action ::', 
 'follow TS Access denied', 
 'CST has Access denied on Matrix (TDM Line),,there is no Outage on CST360 ,,ADSL led down ,,no record on IR ,,CCA right action ', 
 'Create Record on IR Cases and inform customer  4 Hours SLA',




    // 19 

    'If Cst Paid From Bank Check And Payment Not Clear We Will Direct Cst To The Branch:' ,
    'False' , 
    'cst can recharge more than 1 extra quota package one time in the same month', 
    'True ', 
    'In Case Cst Paid From Online Method (APP WE or E-Care ) And Payment Not Clear On Bss The Right Action Will Be :', 
    'Inform CST wait 1H', 
    'No Need to make verification with cst while make Early renewal to him..', 
    'FALSE         ', 
    "If Usage On BSS Like CST360 that's mean the cst has usage issue and should create TT", 
    'FALSE', 
    'if cst is not eligible for balance fraction CCA will create SR :', 
    'FBB Non Tech Request​--billing adjustment--balance fraction not added', 
    ' if CST need to make early renewal CCA should make verification  with him ?', 
    'TRUE ', 
    'If the customer paid through Fawry and the payment is not clear will create TT  and inform CST to wait 24 h SLA', 
    '   FALSE', 
    'if cst subscribed on super 100 G and ask to make early renewal from 111 will be available ?', 
    'FALSE', 
    'If cst paid from branches and payment not clear should ….', 
    'Direct cst to branch ', 
    'If cst asked about renewal date CCA will create SR :', 
    'FBB Non-Tech Inquiry-- Billing-- Renewal date', 
    'CST asked about ( Bank check ) payment method, SR will be', 
    'FBB Non-Tech Inquiry--Payment Methods--Bank Check', 
    'CST line should be suspended to add balance fraction ..', 
    'FALSE', 
    'We can add balance to cst with a maximum ...…. In case his balance not enough to renew his package', 
    '3 LE', 
    'if cst make early renewal he will lose the old quota ?', 
    'TRUE', 
    'IF commercial/government customers request an electronic Bill CCA action .....', 
    'Create TT ', 
    'If Cst Paid From Fawry Service Will reflect on BSS ….', 
    'On spot', 
    'We can make Early renewal to the CST from ..', 
    'BSS', 
    ' We can add balance fraction to cst in case cst need ', 
    'All of the above ', 
    'If the customer asks about the basic package consumption will create SR ..', 
    'FBB Non-Tech - Inquiry>Usage >Basic Quota',





    // 20 

'in case of concession will be 40L.E or 50Giga,, CCA will ', 
 ' create IR to TL', 
 'cst ask for concession there is no outage ID on 360 CCA right action', 
 'search for SR outage on BSS', 
 'we can compensate customer for paid period only', 
 'TRUE',
 'CST has Technical concession,  in case Disapproved Concession CST will received a call', 
 'TRUE', 
 'CST asked about concession on  ticket with update Working from exchange ', 
 'inform cst with concession process', 
 'In case customer asked to revalidate on spot concession, CCA will create ', 
 'IR', 
 'SLA for Technical concession TT  (Billing + CLM) Will be', 
 '2H (from 8:9 PM expect Friday: 2:9 PM', 
 'On Spot cases Will Assign to TL value will be ', 
 '20 to 50G or 12 to 40 L.E', 
 'CST has Technical Concession, we will call cst in the case of approved concession', 
 'FALSE', 
 ' for Major Fault "Maintenance concession CCA will', 
 'inform CST to wait 48h for Automatic Concession', 
 'in on spot concession we must inform cst with amount or GBs within the call', 
 'TRUE', 
 'Double Satisfaction Concession will be ', 
 'quota only', 
 'IF CST deserves concession for 27 hours, concession value will be', 
 '2 days', 
 'in case of concession will be more than 100 Giga or le CCA will create IR with SLA 30 min', 
 'FALSE', 
 'CCA can compensate cst on spot technical concession for TKT with maximum 20 G or 12 L.E', 
 'TRUE', 
 'No need to ask for the CST number for the secondary mobile while creating a concession TT', 
 'FALSE', 
 ' if cst ask about concession and no outage id on CST360 and no bss SR related to outage we must check change location in CST 360  logs', 
 'TRUE', 
 'The compensation request can be submitted starting from … for outage issue', 
 '6h', 
 'If CST is not Satisfied on normal concession CCA will', 
 'create TT to CLM &Billing team', 
 'We can compensate Cst For Ticket BLQ or instability and Clear View result No physical layer', 
 'TRUE',









    // 21 

    'CST has Non-technical concession ,, we will call CST in disapproved concession Only. ', 
    'FALSE', 
    'Enabled by mistake concession SLA .....?', 
    '2 WH', 
    'We can Compensate cst if he change his offering By mistake through E-care within……………  from his Action ', 
    '24 H', 
    'CST can make early renewal on satisfaction concession period ?', 
    'TRUE', 
    'In case cst need to be compensated  by balance  for non tech case will sent the request to TL ', 
    'FALSE', 
    'cst ask about his concession request and follow up after IR SLA​ right SR Will be ', 
    'FBB Non-Tech follow up - Billing Adjustment - ​Concession- Non-Tech TL - after SLA', 
    'Agent can compensate CST (non tech concession) .......?', 
    '5 GB', 
    'Max limit in case TL will compensate CST (non tech concession) .......?', 
    '20 GB ', 
    'SLA for Stolen cable concession without ticket on TTS ?', 
    '21 WD', 
    'complaint concession Created By TL and agent ?', 
    'FALSE', 
    'In case the CST make( change offering or Early Renewal ) more than once by mistake and that a week does not pass between the Two Actions) no need to make verification and will sent TT ', 
    'TRUE', 
    'In case customer asked to revalidate on spot non tech  concession ?', 
    'Create IR and inform CST within 30 Min', 
    ' In case the speed of the customer on cst 360  is ​​less than his speed on BSS, we will make TT with SLA 24 hours', 
    'FALSE', 
    'if cst downgraded by mistake CCA will create TT with SLA :', 
    '2 WH', 
    'in case CCA compensate CST  within the call  for non tech concession CCA should Create IR ?', 
    'TRUE', 
    'if cst ask about stolen cable concession and no data and voice down Ticket on TTS ,your action ', 
    'we will create TT and inform cst he will receive call or SMS within 21 WD', 
    'complain concession will be created from ', 
    'complain team or Team leaders ', 
    'In case CST make Change Package Or Early Renewal and  before Due Date package removed bye root operator. What action needed ?', 
    'Create TT', 
    'Suspension life cycle for prepaid cst after ', 
    '30 days ', 
    'CCA must write TKT NO. in FV concession TT', 
    'True',

    

    // 22 
    'If customer Ask for Suspension , It will be without Required Papers', 
    'FALSE', 
    'In case CST asked about ( resumption after suspension ), Right SR :', 
    'FBB Non-Tech Inquiry>Internet Service>Resumption after Suspension', 
    'If the customer asking about Refund , Right SR :', 
    ' FBB Non-Tech Inquiry---Service Cancellation----Ask for Refund', 
    'The account on BSS  will be transferred to Deactivation  , if the customer has not paid for …….. days since the last day of the last invoice', 
    '180 Days', 
    'In case Customer  paid the package bill within 24 hours, and line is Active on BSS, and Get Online Service in matrix Not Blocked, CCA restarted port ( Problem solved) , CCA', 
    'Create SR  ( FBB Non-Tech Inquiry-- Billing--Restart Port )', 
    'CCA can check from …………. that the service is suspended due to Non-payment of the landline bill through  ( Suspended Customer )  :', 
    'CST 360', 
    ' In case the account on BSS ( Deactivation ) and the Customer wants to pay and activate the service ( There is no Cancellation Num ) , CCA action :', 
    'Transferred Cst to cancellation Q', 
    'The customer can get ( cancellation form ) whether he requests it or not :', 
    'FALSE', 
    'Temporary suspension  SLA :', 
    'On Spot', 
    'In case Customer Want to make  resume the service ( after suspension Upon Customer Request) Can Make It Through :', 
    'All the above', 
    'Retention Team working hours :', 
    ' From 10AM  to 9 PM', 
    'In case customer requests about ( Cancellation number ), the number appears on the System, CCA will inform the cst it and create SR :', 
    ' FBB Non Tech follow up--Service Cancellation--Call back to CRM', 
    'In case the reason of suspension is ( Manual Suspend HK ) , CCA Action :', 
    'Inform Customer that this is because ( did not receive the ONT ) for Hayah Karima', 
    'The customer can cancell the service from exchange without Required papers :', 
    ' False', 
    'CCA should ask customer about reason for cancellation ( Before ) follow cancellation request:', 
    'True', 
    'Corporate customer requests a refund, CCA action:', 
    'Direct cst to the delegate or the corporate department', 
    'The customer can make a Refund from branch without Required papers :', 
    ' False', 
    'If cst complain from refund process, Right sr :', 
    'FBB Non-Tech Complaint ---Service Cancellation----Ask for Refund ', 
    'Customer can request Temporary suspension Through :', 
    'All the above' , 
    "BSS FV CST Paid FV bills But FV is still suspended, CCA Action :",
    "• remove temp suspension from CST 360 " , 
    "CST Can Make Cancellation From WE App Now ",
    "False" , 
    "Direct CST can request Refund VIA WE APP" , 
    "False" , 

    // 23 
    'If you found  (Tel No not in service) appears on ADF and the customer is paying the bills, your action ..', 
    'will activate through the Line Card Function on the ADF.', 
    'Cst want to connect with Exchange manger CCA Action ....', 
    'Direct Cst to Exchange', 
    'While creating  ticket on ADF ,,  Complain Side Code must be :', 
    'خدمة العملاء – شكوى هامة 21 أو خدمة المواطنين 2', 
    'In case CST need to Change Box without any problem  ,, his subscription voice only from WE ,, your action :', 
    'Inform CST his request is not available', 
    'While creating ticket on ADF ,,  Complain Type Code must be :', 
    'بدون حرارة 1', 
    'Cst Need to change Port not Subscribe With Us On Internet ,,, CCA Right Action', 
    'Refer Back to His ISP', 
    'In case there is major fault on ADF tool with reason (اتلاف) or (سرقة),inform cst SLA :', 
    '5 Days', 
    'While creating a ticket on ADF,, an error major fault appeared, your action :', 
    'Act on Major fault', 
    'CST his landline number starting with the number (6), and CST has a problem in voice, your action :', 
    'Direct CST to his company which subscription with it', 
    'Non BSS Customers need to complain agent as he give him (wrong info ) so…', 
    'will create IR and inform cst 24 h', 
    'Required Ticket Data "Mandatory" to create ADF Ticket .....', 
    'All Of Above', 
    'If cst has landline Number Start With (6) that"s mean his number belongs to WE ..?', 
    'FALSE', 
    'In case CST need to change the cable because of problem in the Voice ,,his subscription voice only from WE and subscription internet from another ISP,, your action:', 
    'Check problem with CST and Create ticket on ADF', 
    'For voice only Cst and subscription internet from another ISP ,need to change port from ADSL to VDSL ,, your action', 
    'Direct CST to his company which subscription internet with it', 
    'We can active voice after cst paid landline bills From Which Tool :', 
    'CST360', 
    'CST Need change His/her Box due to has Noise Issue  CCA right Action…', 
    'Follow normal T.S with Cst', 
    'In case CST need to Change Box without any problem ,,, CCA Right Action', 
    'Inform CST his request is not available', 
    'Installation phase will be done ......... SLA ( For MSAN and TDM)', 
    '5 Days', 
    'For Non BSS Customers need to call TL to complaint ,, CCA Right Action', 
    'create I Report Hard Call with complaint type: call back SLA: 1H', 
    'We must inform the customer with the ADF No', 
    'TRUE' , 



    ////////////////////////////////////////////

'Which actions is supported by HDM tool', 
 'Reset cpe', 
 'In Case CCA Check HDM Tool and found it offline so CCA right action', 
 'Restart Port', 
 'CST has unable to obtain Ip and we found CPE Version HG531 CCA right action:', 
 'Restat cpe', 
 'CCA Can check Customer Pool Of His Subscription from NST:', 
 'Query LDAP Profile', 
 'Escalation Suspended Account case SLA will be:', 
 '72h', 
 'While Cst has ( Wrona Nas Port ID Login Jand CCA will Escalate Ticket SO SLAwill be', 
 '2.5h', 
 'CCA Can Change DNS from HDM Tool Function', 
 'Wan Settings', 
 'CCA can Change Default Gateway IP Address from which HDM Function', 
 'Dhcb Setting', 
 'For Escalation Browsing all site case TT Will be ?', 
 'Broadband->Technical->ADSLNDSL->I Care->Browsing', 
 "Customer can open YouTube/ Facebook but contents doesn't appeared first step is ??", 
 'IF CPE accessed try to adjust MTU and DNS [WE then Google DNS]', 
 'In caseCustomer input that he paid the package bill within 24 hours, and line is Active on BSS, and Get Online Service in matrix or new cst 360 Not Blocked.', 
 'Restat port', 
 ' Google DNS IS?', 
 ' 8888/ 88.4.4', 
 ' Ping-t command used to', 
 ' calculate packet loss percentage', 
 ' In case packet lose is Equal or less than 20%, its mean', 
 'No problem from network Side', 
 ' In case Packet lose percentage was 30%, Next step will be...', 
 'ping-ton cpe ip', 
 'In case cst has many accepted logs in last 24 Hr, cca must be sure that not related to restart port or cpe', 
 'True', 
 ' Line Supported by ASSIA and clear view result was (Technical dispatch),CCA Action', 
 'Handle physical instability problem', 
 ' its mandatory to follow logical verification before handle logical instability', 
 ' True', 
 ' In cae est has Ping result from Google P 15%, and there mas packet loss from CPEPand the problem soledamer make Reset&Recondiqure. So the night SRlbe', 
 'LogicalInstability', 
 'ICST using IDM and download rate is not accepted from the fest file CCA Action', 
 'Ping Google lp', 
 ' Check POP Utäizstion Status From', 
 'Ct 360 Tocl', 
 'Escalation Speed Variance case SLA wil be:', 
 '72h', 
 ' Customer has Planned Outage (Downand cal us after estimated time And Has Data DounCase. your action is', 
 'Handle case nomah,', 
 ' In case BSS became don within troubleshooting wth customer, CCA will update full troubleshooting steps done on-Repont TKT ', 
 'True', 
 ' In case customer follow up after the wrap up your action is:', 
 'CCA will continue the troubleshooting which existon I-Report', 
 ' Outages that related to Specific port or frame, SLA is:', 
 '5 Working Days', 
 ' Customer has outage Data Down on CST 360 and call us within first 4 hours, right SR iS:', 
 'FBB Tech Problem>> Outage- Data Down>> within SLA', 
 ' In case we found Submit error or Submit normally with no ticket created on TTS,, SLA is:', 
 '3dys', 
 ' Port time out and Access denied cases override Disable as it consider a normal behavior', 
 'True', 
 ' CST has Access denied,and there is Outage Data Down on CST 360, right action is', 
 'Act as outage rules', 
 ' In case we found "DSL Exchange" name is missing while creating ticket SLA is:', 
 '2wd', 
 ' (TDM Line) CST has Port Time Out on Matrix, No Outage, ADSL led is Down in his CPE, No records created on IR, right action is', 
 'Create Record on IR Cases and inform customer 4 Hours SLA', 
 ' When CCA follow logical instability TS with CST, CST must connect one laptop through wireles ', 
 'Fules', 
 ' In case we found packet loss from cpe IP-0% after we found packet loss from google was-35%., CCA Action', 
 'Escalate to SLS', 
 'Escalation of logical instability (multiple login) must be to.', 
 'Noc', 
 ' while Escalation of logical instability (No multiple login case) SLA is..', 
 'from 2 to 5H', 
 'After follow slowness case TS, Customer download not accepted CCA Action:', 
 'Ping Google Ip', 
 ' Before troubleshooting Slowness case CCA should inform customer to close all opened applications that are using the internet connection:', 
 'True', 
 ' CST need to subscribe in Option pack service CCA Action:', 
 'There is new subscription for Option Pack via branches or 111', 
 ' Slowness Case Escalated To', 
 'Noc', 
 'first priority while cst has slowness in browsing is using:',  
 'Add Google DNS',

] ;

function getData(eqValue){

        for(let i = 0 ; i < data.length; i += 2  ){

        eqValue = (eqValue.trim()).toLowerCase()  ; 
        dataValue =   data[i].trim().toLowerCase() ; 

        if(  eqValue   ==   dataValue ){
                ans.innerHTML = `
                    <p style="color:blue">${data[i]}</p> 
                    <hr style=" width: 50% ; margin: auto ; ">
                    <p style="color:green"> ${data[i+1]}</p> 
                    <span class="num"> ${ parseInt( (i+1)/40 ) + 3 } </span> 
                `;
                break;
        }else{
                if( dataValue.includes(  eqValue ) ){
                    ans.innerHTML = `
                    <p style="color:blue;">${data[i]}</p> 
                    <hr style=" width: 50% ; margin: auto ; ">
                    <p style="color:green;"> ${data[i+1]}</p> 
                    <span class="num"> ${ parseInt( (i+1)/40 ) + 3 } </span>  
                `;
                    break;
                }else{
                    ans.innerHTML = '<p style="color:red"> حاول تمسح جزء من اخر السؤال ومن اول السؤال وابحث تاني ولو مسحت وبرضو مجبش يبقى مش عندي </p> ' ;                }
        }
        

    }
}



get.addEventListener("click", function (){

    getData( eq.value )

} )
















